<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2010-07-26 17:18
return array(
	'tx_feusertools_tcemain' => t3lib_extMgm::extPath('feusertools', 'Classes/Tcemain.php'),
);
?>